version: "3"
tasks:
  start-env:
    desc: Start supabase
    dotenv:
      - .env.local
    cmds:
      - supabase start
      - pnpm drizzle-kit migrate
      - psql $DATABASE_URL --file ./supabase/seed.sql

  stop-env:
    desc: Start supabase
    cmds:
      - supabase stop

  run:
    desc: Run the development server
    cmds:
      - task: start-env
      - pnpm run dev

  integration-test:
    desc: Run integration tests
    cmds:
      - pnpm run test:integration

  apply:*:
    desc: Apply dev infrastructure changes
    dir: ./terraform/application
    vars:
      ENVIRONMENT: "{{index .MATCH 0}}"
    cmds:
      - terraform init -backend-config=config/{{.ENVIRONMENT}}.hcl -reconfigure
      - terraform apply -var-file=config/{{.ENVIRONMENT}}.tfvars -var-file=config/{{.ENVIRONMENT}}.secret.tfvars

  deploy:*:
    desc: Deploy to specified environment
    vars:
      ENVIRONMENT: "{{index .MATCH 0}}"
    cmds:
      - task: "apply:{{.ENVIRONMENT}}"

  build:
    desc: Run formatter, linter, and tests
    cmds:
      - pnpm run fmt
      - pnpm run lint
      - pnpm run test
      - pnpm run test:integration
      - pnpm run build
